{
 "title": "New dashboard Copy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Avg._Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg._Disk",
     "type": "graph",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$col $tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_diskio",
       "select": [
        [
         { "params": [ "Avg._Disk_Queue_Length" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Avg._Disk_Queue_Lenght" ], "type": "alias" }
        ],
        [
         { "params": [ "Avg._Disk_sec/Read" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Avg/_Disk_sec/Read" ], "type": "alias" }
        ],
        [
         { "params": [ "Avg._Disk_sec/Write" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Avg._Disk_sec/Write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-QSBLF3Q" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Read/Write",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read/Write",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 1 },
     "targets": [
      {
       "alias": "$col $tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_disk",
       "select": [
        [
         { "params": [ "Current_Disk_Queue_Length" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Current_Disk_Queue_Lenght" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-QSBLF3Q" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Net",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Net",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col $tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_net",
       "select": [
        [
         { "params": [ "Bytes_Received_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Bytes_Received" ], "type": "alias" }
        ],
        [
         { "params": [ "Bytes_Sent_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Bytes_Sent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-QSBLF3Q" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$col $tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_cpu",
       "select": [
        [
         { "params": [ "Percent_Processor_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Percent_Processor_Time" ], "type": "alias" }
        ],
        [
         { "params": [ "Percent_Idle_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Percent_Idle_Time" ], "type": "alias" }
        ],
        [
         { "params": [ "Percent_User_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Percent_User_Time" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-QSBLF3Q" }
       ]
      }
     ]
    },
    {
     "title": "Processor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "string" }
     ],
     "targets": [
      {
       "alias": "$col $tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_system",
       "select": [
        [
         { "params": [ "Processor_Queue_Length" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Percent_Queue_Lenght_Time" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-QSBLF3Q" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Win Services Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "WebTours",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$tag_display_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "display_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_services",
       "select": [
        [
         { "params": [ "startup_mode" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "display_name", "operator": "=", "value": "webtours" }
       ]
      }
     ]
    },
    {
     "title": "InfluxDB",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$tag_display_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "display_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_services",
       "select": [
        [
         { "params": [ "startup_mode" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "display_name", "operator": "=", "value": "influxdb" }
       ]
      }
     ]
    },
    {
     "title": "Telegraf",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$tag_display_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "display_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_services",
       "select": [
        [
         { "params": [ "startup_mode" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "display_name",
         "operator": "=",
         "value": "Telegraf Data Collector Service"
        }
       ]
      }
     ]
    },
    {
     "title": "Grafana",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$tag_display_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "display_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_services",
       "select": [
        [
         { "params": [ "startup_mode" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "display_name", "operator": "=", "value": "grafana" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$col $tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "select": [
        [
         { "params": [ "Available_Bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Avaliable_Bytes" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$col $tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "select": [
        [
         { "params": [ "Pages_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Pages_persec" ], "type": "alias" }
        ],
        [
         { "params": [ "Page_Faults_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Page_Faults" ], "type": "alias" }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}